/* The following code was generated by JFlex 1.6.1 */

import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>LexicalAnalyzer.flex</tt>
 */
class tester {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\40\1\2\1\53\1\53\1\1\22\0\1\40\1\51\6\0"+
    "\1\54\1\55\1\26\1\16\1\27\1\24\1\41\1\25\1\43\11\42"+
    "\3\0\1\56\3\0\1\32\1\3\1\52\1\12\1\10\1\7\1\20"+
    "\1\50\1\6\2\3\1\44\1\33\1\11\1\31\1\30\1\3\1\22"+
    "\1\45\1\17\6\3\6\0\1\36\1\3\1\52\1\15\1\13\1\5"+
    "\1\21\1\50\1\4\2\3\1\46\1\37\1\14\1\35\1\34\1\3"+
    "\1\23\1\47\1\17\6\3\12\0\1\53\u1fa2\0\1\53\1\53\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\5\3\1\4\2\3\1\5\1\6"+
    "\1\7\1\10\1\3\1\11\1\1\2\12\1\13\1\14"+
    "\1\15\1\3\1\7\2\3\1\11\1\1\1\0\1\16"+
    "\11\3\1\0\1\17\2\0\1\11\2\3\1\0\1\3"+
    "\2\20\1\3\1\20\6\3\1\21\3\3\1\22\2\3"+
    "\1\23\5\3\1\24\1\25\1\26\6\3\1\27\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\136\0\u01d6\0\u0205\0\136\0\136\0\136"+
    "\0\136\0\u0234\0\136\0\u0263\0\u0292\0\136\0\136\0\136"+
    "\0\136\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u02f0\0\215"+
    "\0\353\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6"+
    "\0\u04f5\0\u0524\0\u0263\0\136\0\u02f0\0\u0553\0\u0582\0\u05b1"+
    "\0\u05e0\0\u060f\0\u063e\0\u066d\0\353\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\136\0\u0814\0\u0843"+
    "\0\u0872\0\353\0\u08a1\0\u08d0\0\353\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\u09bb\0\353\0\353\0\136\0\u09ea\0\u0a19\0\u0a48"+
    "\0\u0a77\0\u0aa6\0\u0ad5\0\353\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\6\1\10\1\6"+
    "\1\11\2\6\1\12\2\6\1\13\1\14\2\6\2\15"+
    "\1\16\1\17\1\20\1\21\1\22\3\6\1\22\3\6"+
    "\1\23\1\24\1\25\1\26\5\6\1\3\1\6\1\3"+
    "\1\27\1\30\1\31\1\3\1\4\1\5\1\6\1\7"+
    "\1\6\1\10\1\6\1\11\1\6\1\32\1\12\1\6"+
    "\1\32\1\13\1\14\2\6\2\15\1\16\1\17\1\33"+
    "\1\21\1\34\3\6\1\35\3\6\1\36\1\24\1\25"+
    "\1\26\5\6\1\37\1\32\1\3\1\27\1\30\1\31"+
    "\61\0\1\5\55\0\1\40\1\5\57\0\13\6\1\0"+
    "\5\6\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\2\6\1\41\3\6\1\42\2\6\1\42\1\6\1\0"+
    "\5\6\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\4\6\1\41\1\6\1\42\2\6\1\42\1\6\1\0"+
    "\5\6\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\6\6\1\43\2\6\1\44\1\6\1\0\5\6\4\0"+
    "\10\6\2\0\2\6\1\45\4\6\1\0\1\6\7\0"+
    "\6\6\1\44\2\6\1\46\1\6\1\0\5\6\4\0"+
    "\10\6\2\0\4\6\1\47\2\6\1\0\1\6\7\0"+
    "\13\6\1\0\5\6\4\0\10\6\2\0\6\6\1\50"+
    "\1\0\1\6\7\0\5\6\1\51\2\6\1\51\2\6"+
    "\1\0\5\6\4\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\3\6\2\52\4\0\10\6\2\0"+
    "\7\6\1\0\1\6\7\0\13\53\1\0\5\53\4\0"+
    "\10\53\1\0\1\54\2\0\5\53\1\0\1\53\46\0"+
    "\2\25\13\0\1\55\1\56\1\57\13\32\1\55\5\32"+
    "\4\55\10\32\2\55\7\32\1\55\1\32\1\0\4\55"+
    "\1\56\1\57\50\55\1\0\3\55\3\0\13\6\1\0"+
    "\3\6\1\60\1\52\4\0\10\6\2\0\7\6\1\0"+
    "\1\6\7\0\13\6\1\0\3\6\1\52\1\61\4\0"+
    "\10\6\2\0\7\6\1\0\1\6\16\0\1\62\2\0"+
    "\1\62\44\0\13\6\1\0\1\63\4\6\4\0\10\6"+
    "\2\0\7\6\1\0\1\6\7\0\7\6\1\64\2\6"+
    "\1\65\1\0\5\6\4\0\10\6\2\0\7\6\1\0"+
    "\1\6\7\0\7\6\1\65\2\6\1\65\1\0\5\6"+
    "\4\0\10\6\2\0\7\6\1\0\1\6\7\0\13\6"+
    "\1\0\5\6\4\0\10\6\2\0\3\6\1\66\3\6"+
    "\1\0\1\6\7\0\7\6\1\65\2\6\1\67\1\0"+
    "\5\6\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\13\6\1\0\5\6\4\0\10\6\2\0\5\6\1\70"+
    "\1\6\1\0\1\6\7\0\5\6\1\71\2\6\1\71"+
    "\2\6\1\0\5\6\4\0\10\6\2\0\7\6\1\0"+
    "\1\6\7\0\13\6\1\0\5\6\4\0\2\6\1\72"+
    "\3\6\1\72\1\6\2\0\7\6\1\0\1\6\7\0"+
    "\1\6\1\73\1\6\1\73\7\6\1\0\5\6\4\0"+
    "\10\6\2\0\7\6\1\0\1\6\6\0\1\57\55\0"+
    "\1\56\1\57\57\0\1\6\1\73\1\6\1\73\7\6"+
    "\1\0\5\6\4\0\1\6\1\74\6\6\2\0\7\6"+
    "\1\0\1\6\7\0\1\6\1\73\1\6\1\73\7\6"+
    "\1\0\5\6\4\0\5\6\1\75\2\6\2\0\7\6"+
    "\1\0\1\6\35\0\1\76\3\0\1\76\24\0\5\6"+
    "\1\77\2\6\1\77\2\6\1\0\5\6\4\0\10\6"+
    "\2\0\7\6\1\0\1\6\7\0\3\6\1\100\3\6"+
    "\1\101\3\6\1\0\5\6\4\0\10\6\2\0\7\6"+
    "\1\0\1\6\7\0\5\6\1\102\5\6\1\0\5\6"+
    "\4\0\10\6\2\0\7\6\1\0\1\6\7\0\1\6"+
    "\1\103\10\6\1\104\1\0\5\6\4\0\10\6\2\0"+
    "\7\6\1\0\1\6\7\0\10\6\1\102\2\6\1\0"+
    "\5\6\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\6\6\1\105\2\6\1\105\1\6\1\0\5\6\4\0"+
    "\10\6\2\0\7\6\1\0\1\6\7\0\7\6\1\106"+
    "\2\6\1\106\1\0\5\6\4\0\10\6\2\0\7\6"+
    "\1\0\1\6\7\0\6\6\1\107\2\6\1\107\1\6"+
    "\1\0\5\6\4\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\1\6\1\110\3\6\4\0\10\6"+
    "\2\0\7\6\1\0\1\6\7\0\13\6\1\0\2\6"+
    "\1\111\2\6\4\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\1\6\2\112\2\6\4\0\10\6"+
    "\2\0\7\6\1\0\1\6\7\0\4\6\1\113\6\6"+
    "\1\0\5\6\4\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\5\6\4\0\1\6\1\114\6\6"+
    "\2\0\7\6\1\0\1\6\7\0\2\6\1\113\10\6"+
    "\1\0\5\6\4\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\5\6\4\0\5\6\1\114\2\6"+
    "\2\0\7\6\1\0\1\6\7\0\13\6\1\0\5\6"+
    "\2\0\1\115\1\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\1\116\4\6\4\0\10\6\2\0"+
    "\7\6\1\0\1\6\7\0\13\6\1\0\3\6\1\117"+
    "\1\6\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\13\6\1\0\4\6\1\120\4\0\10\6\2\0\7\6"+
    "\1\0\1\6\7\0\5\6\1\121\2\6\1\121\2\6"+
    "\1\0\5\6\4\0\10\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\5\6\2\0\1\26\1\0\10\6"+
    "\2\0\7\6\1\0\1\6\7\0\13\6\1\0\5\6"+
    "\4\0\2\6\1\122\5\6\2\0\7\6\1\0\1\6"+
    "\7\0\13\6\1\0\5\6\4\0\6\6\1\123\1\6"+
    "\2\0\7\6\1\0\1\6\7\0\13\6\1\0\3\6"+
    "\2\124\4\0\10\6\2\0\7\6\1\0\1\6\7\0"+
    "\13\6\1\0\5\6\4\0\3\6\1\125\4\6\2\0"+
    "\7\6\1\0\1\6\7\0\13\6\1\0\5\6\4\0"+
    "\7\6\1\125\2\0\7\6\1\0\1\6\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2820];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\7\1\1\11\2\1\4\11\1\1\1\11"+
    "\2\1\4\11\6\1\1\0\12\1\1\0\1\11\2\0"+
    "\3\1\1\0\13\1\1\11\16\1\1\11\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
Main m = new Main();
List<String> words = new ArrayList<String>();
List<String> line = new ArrayList<String>();
boolean PR = false;
public void program(boolean x){
         this.PR=x;

   }
   public void identifier(String x, int y) {
      
   if(PR == false){
   if(words.isEmpty()== true){
   words.add(x);
   line.add(x + " " +Integer.toString(y+1));
   }
   else { boolean t = true;
   for(int i = 0; i < words.size(); i++){
   if(x.equals(words.get(i)))
   t = false;
                           }
   if(t== true){ words.add(x);
              line.add(x + " " + Integer.toString(y+1));}                      

   }}
   else this.PR = false;


   }
   public void BinaryOP(String x){
   
    switch (x) {
            case ".AND.":
           m.sym(LexicalUnit.AND,x);
            
                     break;
            case ".OR.":
            m.sym(LexicalUnit.OR,x);
            
                     break;
            case ".EQ.": 
            m.sym(LexicalUnit.EQUAL_COMPARE,x);
            
                     break;
            case ".GE.":
            m.sym(LexicalUnit.GREATER_EQUAL,x);
            
                     break;
            case ".GT.":
            m.sym(LexicalUnit.GREATER,x);
            
                     break;
            case ".Le.":
            m.sym(LexicalUnit.SMALLER_EQUAL,x);
            
                     break;
            case ".LT.":
            m.sym(LexicalUnit.SMALLER,x);
            
                     break;
            case ".NE.":
            m.sym(LexicalUnit.DIFFERENT,x);
            
                     break;
            
        }}
    public void last(){
         System.out.println("Identifiers");
         Collections.sort(line);
     if(words != null){
    for(int i = 0; i< words.size(); i++){
      System.out.println(line.get(i));
         }
                              }
     else System.out.print("No Varnames");
      }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  tester(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    last();

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.print(yytext());
            }
          case 25: break;
          case 2: 
            { m.sym(LexicalUnit.ENDLINE," ");
            }
          case 26: break;
          case 3: 
            { identifier(yytext(),yyline);
				m.sym(LexicalUnit.VARNAME,yytext());
            }
          case 27: break;
          case 4: 
            { m.sym(LexicalUnit.PLUS,yytext());
            }
          case 28: break;
          case 5: 
            { m.sym(LexicalUnit.MINUS,yytext());
            }
          case 29: break;
          case 6: 
            { m.sym(LexicalUnit.DIVIDE,yytext());
            }
          case 30: break;
          case 7: 
            { m.sym(LexicalUnit.TIMES,yytext());
            }
          case 31: break;
          case 8: 
            { m.sym(LexicalUnit.COMMA,yytext());
            }
          case 32: break;
          case 9: 
            { 
            }
          case 33: break;
          case 10: 
            { m.sym(LexicalUnit.NUMBER,yytext());
            }
          case 34: break;
          case 11: 
            { m.sym(LexicalUnit.LEFT_PARENTHESIS,yytext());
            }
          case 35: break;
          case 12: 
            { m.sym(LexicalUnit.RIGHT_PARENTHESIS,yytext());
            }
          case 36: break;
          case 13: 
            { m.sym(LexicalUnit.EQUAL,yytext());
            }
          case 37: break;
          case 14: 
            { m.sym(LexicalUnit.IF,yytext());
            }
          case 38: break;
          case 15: 
            { BinaryOP(yytext());
            }
          case 39: break;
          case 16: 
            { m.sym(LexicalUnit.END,yytext());
            }
          case 40: break;
          case 17: 
            { m.sym(LexicalUnit.DO,yytext());
            }
          case 41: break;
          case 18: 
            { m.sym(LexicalUnit.ELSE,yytext());
            }
          case 42: break;
          case 19: 
            { m.sym(LexicalUnit.THEN,yytext());
            }
          case 43: break;
          case 20: 
            { m.sym(LexicalUnit.ENDIF,yytext());
            }
          case 44: break;
          case 21: 
            { m.sym(LexicalUnit.ENDDO,yytext());
            }
          case 45: break;
          case 22: 
            { m.sym(LexicalUnit.READ,yytext());
            }
          case 46: break;
          case 23: 
            { m.sym(LexicalUnit.INTEGER,yytext());
            }
          case 47: break;
          case 24: 
            { program(true);
				m.sym(LexicalUnit.PROGRAM,yytext());
            }
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java tester [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        tester scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new tester(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
